### PR TITLE
Fedora install script and other improvements

### PR DESCRIPTION
**Pull request by kuba3351**
I implemented an fedora.sh install script to install nwg-shell on Fedora. I also made a small improvements to other scripts. Stopping the script if any error occurs and checking if script is running on root. It is a common mistake to run the script as root. If this happen, the nwg-installer installs config files in root's home directory instead of user. I don't know how to propose changes on wiki to mention that there is a fedora install script. Scripts was tested on Fedora Sway Spin clean installed.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Thank you!

> I don't know how to propose changes on wiki to mention that there is a fedora install script.

You should be able to edit Wiki pages through the web browser. Just give me an hour to restructure the current content, and make some space for distros other than Arch. I'll place some dummy content, for you to replace it with what should be written.

**Comment by kuba3351** [comment]
Thank you for mwrging this. Unfortunately I don't have an option to edit your wiki. Github allow wiki editing for collaboratora by default but you can change this: https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

So, I will write a wiki when I will be able to edit.

**Comment by nwg-piotr** [comment]
> So, I will write a wiki when I will be able to edit.

Very true. It should be possible now.

**Comment by kuba3351** [comment]
Written the wiki.

**Comment by nwg-piotr** [comment]
Excellent, thank you. Let's see if it's enough for a newcomer like me to install Fedora. :)

**Comment by nwg-piotr** [comment]
It was easy enough. First impression:

- missing `pamixer` package -> volume controll does not work
- missing `/usr/share/pixmaps/azote.svg` icon (`azote` package issue)

Also: the current nwg-shell-config version (0.4.14) uses the [update indicator](https://github.com/nwg-piotr/nwg-shell-config/blob/master/nwg_shell_config/update_indicator.py) script, that adds a tray update notifier. Do you think it could support Fedora? Would you like to contribute?

**Comment by kuba3351** [comment]
Hello

> Also: the current nwg-shell-config version (0.4.14) uses the [update indicator](https://github.com/nwg-piotr/nwg-shell-config/blob/master/nwg_shell_config/update_indicator.py) script, that adds a tray update notifier. Do you think it could support Fedora? Would you like to contribute?

Yes, I will try to contribute and add support for this

> missing /usr/share/pixmaps/azote.svg icon (azote package issue

Azote package is available in the official Fedora repo, so it will rrquire to fire a bug in bugzilla to be fixed

> missing pamixer package -> volume controll does not work

Pamixer is available in the Copr repository, so it can be fixed by adding pamixer as a dependency of nwg-shell or another subpackage, but I cannot do this right now because these packages are someone else project. I have to create my fork of this and try to fix the issues and upgrade packages to a never versions

**Comment by nwg-piotr** [comment]
Great! Let's continue on the appropriate [Discussions thread](https://github.com/nwg-piotr/nwg-shell/discussions/38#top).

I announced your work on Mastodon, and had some good reactions. https://fosstodon.org/@nwgpiotr/109809472128462464

**Pull request merged**
